<template>
  <div class="about container">
    <section class="section">
      <p class="title">The Game</p>
      <p class="subtitle">
        History Guesser is an educational game where you are matched with a random figure from history.

        The goal is to figure out who it is by talking to them.  Maybe it is Leonardo da Vinci.. or Genghis Kahn.

        You have a limited amount of questions you can ask, and will only get limited information back -- so choose wisely!
      </p>
    </section>
    <section class="section">

      <p class="title">How it works</p>
      <p class="subtitle">
        Since you can't actually speak to the real people, we are using OpenAI's davinci AI to act like random historical figures.
        Behind the scenes, The AI is instructed to be a random person.  And then a conversation can be had!
      </p>
      <p class="subtitle">
        None of the responses to any questions are precanned by us.  They are 100% generated by the AI.  We just tell the AI to behave like a specific person.
      </p>

      <div>
        <span class="has-text-weight-bold has-text-danger">Warning</span>: This is powered by AI.  Some answers will be off, but most will be accurate.
      </div>
      <div>
        We try our best to accept multple versions of names and places, and everything is case sensitive. Sorry for any typos/mistakes on our part!
      </div>
    </section>

    <section class="section">
      <p class="title">Why can't I say anything to the AI / historical figure?</p>
      <p class="subtitle">
        Two big reasons.  
      </p>
        
      <p class="subtitle">
        1. Allowing unfiltered chat to an AI can result in off topic, inapropriate, or abusive behavior.  Every now and then
        a question can make a very biased answer.  For example, if we ask "What did you invent?", the AI really wants to say something like
        "I invented the computer", or "I invented the internet", no matter what historical figure we tell it to be.
      </p>

      <p class="subtitle">
        2. Also there are a lot of ways to ask questions that make the game easy.  Like, "what are you most famous for?" will pretty much always
        give the answer away immediately.
      </p>
      <p class="subtitle">
        By instead using a very large list of questions we've tested, we can make a more fun & reliable game.
      </p>
    </section>


  </div>
</template>
